package com.caselock.entity.enums;

public enum AuditAction {
    LOGIN,
    LOGOUT,
    LOGIN_FAILED,
    CASE_CREATED,
    CASE_UPDATED,
    CASE_STATUS_CHANGED,
    CASE_CLOSED,
    CASE_ARCHIVED,
    EVIDENCE_UPLOADED,
    EVIDENCE_ACCESSED,
    EVIDENCE_DOWNLOADED,
    EVIDENCE_TRANSFERRED,
    EVIDENCE_UPDATED,
    EVIDENCE_DELETE_ATTEMPT,
    INTEGRITY_VERIFIED,
    USER_CREATED,
    USER_UPDATED,
    USER_DISABLED,
    ROLE_CHANGED,
    PASSWORD_RESET,
    UNAUTHORIZED_ACCESS_ATTEMPT,
    REPORT_GENERATED
}
